const DB='expiryrx_pilot_v1';
const tabs=['Dashboard','Inventory','Receive','Transfers','Verification','Audit','Corporate'];
let state=load(); let current='Dashboard';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function uid(){return (crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2))}
function isoIn(days){let d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function days(exp){return Math.ceil((new Date(exp+'T23:59:59')-new Date())/86400000)}
function status(exp){let d=days(exp); if(d<0)return['EXPIRED','red']; if(d<=30)return['REMOVE/RETURN','red']; if(d<=60)return['MANAGER ALERT','amber']; if(d<=90)return['PRIORITY','amber']; if(d<=120)return['TRANSFER/USE-FIRST','amber']; if(d<=180)return['WATCH','green']; return['OK','green']}
function storeName(id){return state.stores.find(s=>s.id===id)?.name||id}
function save(){localStorage.setItem(DB,JSON.stringify(state));render()}
function log(action,detail,store='SYSTEM'){state.audit.unshift({id:uid(),ts:new Date().toISOString(),user:$('#roleSelect')?.value||'Pharmacist',action,detail,store}); state.audit=state.audit.slice(0,300)}
function load(){let raw=localStorage.getItem(DB);if(raw)try{return JSON.parse(raw)}catch(e){}return seed()}
function seed(){return {stores:[
{id:'S101',name:'Pilot Pharmacy #101 — Raleigh',city:'Raleigh, NC',velocity:{ozempic:1,eliquis:4,mounjaro:2}},
{id:'S207',name:'Pilot Pharmacy #207 — Durham',city:'Durham, NC',velocity:{ozempic:11,eliquis:7,mounjaro:9}},
{id:'S331',name:'Pilot Pharmacy #331 — Cary',city:'Cary, NC',velocity:{ozempic:5,eliquis:3,mounjaro:4}}],
inv:[
{id:uid(),name:'Ozempic 2 mg',key:'ozempic',gtin:'00301694772127',lot:'OZ24091',exp:isoIn(42),qty:8,loc:'Refrigerator 1',value:900,store:'S101',serial:'SN804811'},
{id:uid(),name:'Eliquis 5 mg',key:'eliquis',gtin:'00300030894218',lot:'EL551A',exp:isoIn(73),qty:3,loc:'Shelf C4',value:520,store:'S101',serial:'SN331277'},
{id:uid(),name:'Amoxicillin 500 mg',key:'amoxicillin',gtin:'00300932264050',lot:'AMX804',exp:isoIn(118),qty:8,loc:'Shelf A7',value:18,store:'S101',serial:''},
{id:uid(),name:'Mounjaro 10 mg',key:'mounjaro',gtin:'00300021471805',lot:'MJ7712',exp:isoIn(24),qty:2,loc:'Refrigerator 2',value:1050,store:'S101',serial:'SN928118'},
{id:uid(),name:'Ozempic 2 mg',key:'ozempic',gtin:'00301694772127',lot:'OZ25010',exp:isoIn(190),qty:4,loc:'Refrigerator 1',value:900,store:'S207',serial:'SN901332'},
{id:uid(),name:'Mounjaro 10 mg',key:'mounjaro',gtin:'00300021471805',lot:'MJ8091',exp:isoIn(150),qty:7,loc:'Refrigerator 1',value:1050,store:'S207',serial:'SN613590'},
{id:uid(),name:'Eliquis 5 mg',key:'eliquis',gtin:'00300030894218',lot:'EL660B',exp:isoIn(210),qty:6,loc:'Shelf B2',value:520,store:'S331',serial:'SN715552'}], audit:[], transfers:[], verifications:[]}}
function nav(){ $('#nav').innerHTML=tabs.map(t=>`<button class="${t===current?'active':''}" data-tab="${t}">${t}</button>`).join(''); $$('#nav button').forEach(b=>b.onclick=()=>{current=b.dataset.tab;render()})}
function render(){nav(); const fn={Dashboard:dashboard,Inventory:inventory,Receive:receive,Transfers:transfers,Verification:verification,Audit:audit,Corporate:corporate}[current]; $('#app').innerHTML=fn(); bind()}
function totals(inv=state.inv){return {units:inv.reduce((s,x)=>s+x.qty,0),d30:inv.filter(x=>days(x.exp)<=30).reduce((s,x)=>s+x.qty,0),d90:inv.filter(x=>days(x.exp)>30&&days(x.exp)<=90).reduce((s,x)=>s+x.qty,0),risk:inv.filter(x=>days(x.exp)<=90).reduce((s,x)=>s+x.qty*x.value,0),lots:inv.length}}
function metrics(t){return `<section class="metrics">${[['Units Tracked',t.units,'All active lots'],['Lots',t.lots,'Lot-level visibility'],['≤30 Days',t.d30,'Immediate action'],['31–90 Days',t.d90,'Priority inventory'],['Value at Risk',money(t.risk),'≤90-day retail-cost proxy']].map(x=>`<div class="metric"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="note">${x[2]}</div></div>`).join('')}</section>`}
function inventoryRows(items){return items.sort((a,b)=>new Date(a.exp)-new Date(b.exp)).map(x=>{let s=status(x.exp);return `<tr><td><span class="pill ${s[1]}">${s[0]}</span></td><td><b>${esc(x.name)}</b><div class="muted">${esc(x.gtin)}</div></td><td>${esc(x.lot)}</td><td>${x.exp}<div class="muted">${days(x.exp)} days</div></td><td>${x.qty}</td><td>${esc(x.loc)}</td><td>${esc(storeName(x.store))}</td><td><button class="mini act" data-id="${x.id}">Actions</button></td></tr>`}).join('')||`<tr><td colspan="8" class="empty">No active inventory.</td></tr>`}
function dashboard(){let t=totals();let risky=state.inv.filter(x=>days(x.exp)<=90).sort((a,b)=>days(a.exp)-days(b.exp));let opts=suggestions();return `<div class="hero"><div><div class="kicker" style="color:#bfe8d5">Pilot Command Center</div><h1>Stop expiration loss before it happens.</h1><p>ExpiryRx tracks inventory by lot, prioritizes FEFO, surfaces exception checks, and recommends inter-store transfers for stock likely to expire.</p></div><div class="heroMetric"><span>Potential value protected</span><b>${money(opts.reduce((s,x)=>s+x.value,0))}</b><small>from current transfer opportunities</small></div></div>${metrics(t)}<div class="grid2"><section class="card"><h2>Priority Queue</h2><div class="sub">Soonest-expiring active inventory across pilot stores.</div><div class="tablewrap"><table><thead><tr><th>Priority</th><th>Product</th><th>Lot</th><th>Expires</th><th>Qty</th><th>Location</th><th>Store</th><th></th></tr></thead><tbody>${inventoryRows(risky.slice(0,8))}</tbody></table></div></section><section class="card"><h2>Recommended Transfers</h2><div class="sub">Demo rules combine days-to-expiry, on-hand quantity and simulated store velocity.</div>${opts.length?opts.slice(0,4).map(o=>`<div class="riskrow"><div><b>${esc(o.name)}</b><div class="muted">${esc(storeName(o.from))} → ${esc(storeName(o.to))}</div><div class="muted">${o.qty} units • ${o.days} days left</div></div><div><div class="bigmoney">${money(o.value)}</div><span class="pill blue">Avoidable risk</span></div></div>`).join(''):`<div class="empty">No transfer opportunities detected.</div>`}</section></div>`}
function inventory(){return `<div class="titleline"><div><h1>Inventory</h1><div class="muted">Lot-level inventory across all pilot pharmacies.</div></div><div class="btns"><button class="btn primary" id="goReceive">+ Receive</button><button class="btn ghost" id="export">Export CSV</button></div></div><section class="card"><div class="tablewrap"><table><thead><tr><th>Priority</th><th>Product</th><th>Lot</th><th>Expires</th><th>Qty</th><th>Location</th><th>Store</th><th></th></tr></thead><tbody>${inventoryRows(state.inv)}</tbody></table></div></section>`}
function receive(){return `<div class="titleline"><div><h1>Receive Inventory</h1><div class="muted">Capture product identifier, lot, expiration, quantity and storage location at receiving.</div></div></div><section class="card"><div class="scanner"><b>2D / GS1 DataMatrix pilot input</b><div class="muted">Paste or scan an element string such as (01)00301694772127(17)270430(10)LOT123(21)SERIAL9. The pilot parser will populate GTIN, expiry, lot and serial.</div><div style="display:flex;gap:8px;margin-top:10px"><input id="scanInput" style="flex:1" placeholder="Scan or paste GS1 element string"><button class="btn secondary" id="parseScan">Parse Scan</button></div></div><form id="receiveForm" class="formgrid" style="margin-top:16px"><div class="field full"><label>Medication / Product</label><input name="name" required placeholder="e.g., Ozempic 2 mg"></div><div class="field"><label>GTIN / NDC</label><input name="gtin" required></div><div class="field"><label>Lot</label><input name="lot" required></div><div class="field"><label>Expiration</label><input name="exp" type="date" required></div><div class="field"><label>Serial</label><input name="serial"></div><div class="field"><label>Quantity</label><input name="qty" type="number" min="1" value="1" required></div><div class="field"><label>Storage Location</label><input name="loc" required placeholder="Shelf C4 / Refrigerator 1"></div><div class="field"><label>Unit Value ($)</label><input name="value" type="number" min="0" step=".01" value="0"></div><div class="field"><label>Store</label><select name="store">${state.stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field full"><button class="btn primary" type="submit">Save Received Inventory</button></div></form></section>`}
function parseGS1(raw){let out={};let patterns={gtin:/\(01\)(\d{14})/,exp:/\(17\)(\d{6})/,lot:/\(10\)([^()]+)/,serial:/\(21\)([^()]+)/};for(let [k,r] of Object.entries(patterns)){let m=raw.match(r);if(m)out[k]=m[1]}if(out.exp){let y='20'+out.exp.slice(0,2),m=out.exp.slice(2,4),d=out.exp.slice(4,6);out.exp=`${y}-${m}-${d}`}return out}
function suggestions(){let out=[];for(let x of state.inv){let d=days(x.exp); if(d>120||x.qty<2)continue;let src=state.stores.find(s=>s.id===x.store),vsrc=src?.velocity?.[x.key]||1;let candidates=state.stores.filter(s=>s.id!==x.store).map(s=>({s,v:s.velocity?.[x.key]||0})).sort((a,b)=>b.v-a.v);if(!candidates.length||candidates[0].v<=vsrc)continue;let move=Math.max(1,Math.min(x.qty-1,Math.ceil(x.qty*.75)));out.push({itemId:x.id,name:x.name,from:x.store,to:candidates[0].s.id,qty:move,days:d,value:move*x.value})}return out.sort((a,b)=>b.value-a.value)}
function transfers(){let opts=suggestions();return `<div class="titleline"><div><h1>Transfer Intelligence</h1><div class="muted">Move short-dated stock toward stores with stronger simulated utilization.</div></div></div><section class="card"><h2>Recommended</h2><div class="sub">Pilot recommendations are illustrative and require pharmacist/manager approval.</div>${opts.length?opts.map(o=>`<div class="riskrow"><div><b>${esc(o.name)}</b><div>${esc(storeName(o.from))} → ${esc(storeName(o.to))}</div><div class="muted">${o.qty} units • expires in ${o.days} days</div></div><div><div class="bigmoney">${money(o.value)}</div><button class="btn secondary approveTransfer" data-id="${o.itemId}" data-to="${o.to}" data-qty="${o.qty}">Approve Transfer</button></div></div>`).join(''):`<div class="empty">No transfers recommended.</div>`}</section><section class="card"><h2>Transfer History</h2>${state.transfers.length?`<div class="tablewrap"><table><thead><tr><th>Date</th><th>Product</th><th>From</th><th>To</th><th>Qty</th><th>Status</th></tr></thead><tbody>${state.transfers.map(t=>`<tr><td>${new Date(t.ts).toLocaleString()}</td><td>${esc(t.name)}</td><td>${esc(storeName(t.from))}</td><td>${esc(storeName(t.to))}</td><td>${t.qty}</td><td><span class="pill green">${t.status}</span></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">No transfer history yet.</div>`}</section>`}
function verification(){let list=state.inv.filter(x=>days(x.exp)<=120).sort((a,b)=>days(a.exp)-days(b.exp));return `<div class="titleline"><div><h1>Monthly Verification</h1><div class="muted">Exception-based shelf check: verify only inventory requiring near-term attention.</div></div><div class="btns"><button class="btn primary" id="verifyAll">Mark Listed Items Verified</button></div></div><div class="callout"><b>${list.length} lots require verification.</b> This pilot deliberately keeps a physical exception check as a safety control rather than assuming software inventory is perfect.</div><section class="card"><div class="tablewrap"><table><thead><tr><th>Product</th><th>Lot</th><th>Store</th><th>Location</th><th>Expires</th><th>Last Verified</th></tr></thead><tbody>${list.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.lot)}</td><td>${esc(storeName(x.store))}</td><td>${esc(x.loc)}</td><td>${x.exp}<div class="muted">${days(x.exp)} days</div></td><td>${x.verified?new Date(x.verified).toLocaleDateString():'—'}</td></tr>`).join('')}</tbody></table></div></section>`}
function audit(){return `<div class="titleline"><div><h1>Audit Trail</h1><div class="muted">Every pilot inventory action is recorded with role, time and store context.</div></div></div><section class="card audit">${state.audit.length?state.audit.map(a=>`<div><b>${esc(a.action)}</b> — ${esc(a.detail)}<br><span class="muted">${new Date(a.ts).toLocaleString()} • ${esc(a.user)} • ${esc(a.store==='SYSTEM'?'System':storeName(a.store))}</span></div>`).join(''):`<div class="empty">Actions will appear here as you use the pilot.</div>`}</section>`}
function corporate(){let t=totals();return `<div class="titleline"><div><h1>Corporate View</h1><div class="muted">Portfolio-level expiration exposure and pharmacy-by-pharmacy action load.</div></div></div>${metrics(t)}<section class="card"><h2>Pilot Pharmacy Scorecard</h2><div class="storegrid">${state.stores.map(s=>{let inv=state.inv.filter(x=>x.store===s.id),st=totals(inv),risk90=st.risk;return `<div class="storecard"><div class="kicker">${esc(s.city)}</div><h3>${esc(s.name)}</h3><div class="bigmoney">${money(risk90)}</div><div class="muted">value at risk ≤90 days</div><div class="bar"><i style="width:${Math.min(100,risk90/20000*100)}%"></i></div><div style="margin-top:10px">${st.units} units • ${st.lots} lots • ${st.d30} units ≤30 days</div></div>`}).join('')}</div></section><section class="card"><h2>Production Integration Boundary</h2><div class="callout warning"><b>Pilot uses synthetic inventory and browser storage.</b> Production deployment should replace local storage with an authenticated API + database, integrate approved dispensing/inventory feeds, validate barcode handling against pharmacy workflows, and complete security/compliance review before real medication data is used.</div></section>`}
function actionModal(id){let x=state.inv.find(v=>v.id===id);if(!x)return;$('#modalContent').innerHTML=`<div class="modalhead"><h3>${esc(x.name)} — Lot ${esc(x.lot)}</h3><div class="muted">${esc(storeName(x.store))} • ${x.qty} units • expires ${x.exp}</div></div><div class="modalbody"><div class="btns"><button class="btn secondary doAction" data-kind="Dispensed">Dispense 1</button><button class="btn secondary doAction" data-kind="Returned">Return all</button><button class="btn secondary doAction" data-kind="Quarantined">Quarantine</button><button class="btn danger doAction" data-kind="Destroyed">Destroy all</button></div></div><div class="modalfoot"><button class="btn ghost" id="closeModal">Close</button></div>`;$('#modal').showModal();$('#closeModal').onclick=()=>$('#modal').close();$$('.doAction').forEach(b=>b.onclick=()=>{let kind=b.dataset.kind;if(kind==='Dispensed'){x.qty--;log(kind,`${x.name} lot ${x.lot}: 1 unit removed`,x.store)}else if(kind==='Quarantined'){x.quarantined=true;log(kind,`${x.name} lot ${x.lot} marked quarantined`,x.store)}else{log(kind,`${x.name} lot ${x.lot}: ${x.qty} units removed`,x.store);state.inv=state.inv.filter(v=>v.id!==id)}if(x.qty<=0)state.inv=state.inv.filter(v=>v.id!==id);$('#modal').close();save()})}
function approve(itemId,to,qty){let x=state.inv.find(v=>v.id===itemId);if(!x||qty>x.qty)return;let from=x.store;x.qty-=qty;let newItem={...x,id:uid(),store:to,qty,loc:'Transfer Receiving',verified:null};state.inv.push(newItem);if(x.qty<=0)state.inv=state.inv.filter(v=>v.id!==itemId);state.transfers.unshift({id:uid(),ts:new Date().toISOString(),name:x.name,from,to,qty,status:'Approved'});log('Transfer Approved',`${qty} ${x.name} moved ${storeName(from)} → ${storeName(to)}`,from);save()}
function exportCSV(){let rows=[['Product','GTIN','Lot','Expiration','Qty','Location','UnitValue','Store','Serial'],...state.inv.map(x=>[x.name,x.gtin,x.lot,x.exp,x.qty,x.loc,x.value,storeName(x.store),x.serial])];let csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');let blob=new Blob([csv],{type:'text/csv'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='expiryrx-pilot-inventory.csv';a.click();URL.revokeObjectURL(u)}
function bind(){ $$('.act').forEach(b=>b.onclick=()=>actionModal(b.dataset.id)); let r=$('#roleSelect');if(r)r.onchange=()=>{}; if($('#goReceive'))$('#goReceive').onclick=()=>{current='Receive';render()};if($('#export'))$('#export').onclick=exportCSV;if($('#parseScan'))$('#parseScan').onclick=()=>{let o=parseGS1($('#scanInput').value),f=$('#receiveForm');if(o.gtin)f.gtin.value=o.gtin;if(o.lot)f.lot.value=o.lot;if(o.exp)f.exp.value=o.exp;if(o.serial)f.serial.value=o.serial};if($('#receiveForm'))$('#receiveForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),name=f.get('name').trim(),key=name.toLowerCase().split(/\s+/)[0].replace(/[^a-z]/g,'');let x={id:uid(),name,key,gtin:f.get('gtin').trim(),lot:f.get('lot').trim(),exp:f.get('exp'),serial:f.get('serial').trim(),qty:Number(f.get('qty')),loc:f.get('loc').trim(),value:Number(f.get('value')||0),store:f.get('store')};state.inv.push(x);log('Inventory Received',`${x.qty} ${x.name}, lot ${x.lot}, expires ${x.exp}`,x.store);current='Inventory';save()};$$('.approveTransfer').forEach(b=>b.onclick=()=>approve(b.dataset.id,b.dataset.to,Number(b.dataset.qty)));if($('#verifyAll'))$('#verifyAll').onclick=()=>{let now=new Date().toISOString();let list=state.inv.filter(x=>days(x.exp)<=120);list.forEach(x=>x.verified=now);log('Monthly Verification',`${list.length} exception lots verified`,'SYSTEM');save()}}
render();
