<?php
/**
 * Database schema and access helpers.
 *
 * @package BlueRidgeMailer
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Owns the two custom tables: campaigns (drafts + their lifecycle) and
 * recipients (the coaching-lead list, including unsubscribe state).
 */
class BRM_DB {

	const DB_VERSION = '1.0.0';

	/**
	 * Campaign statuses.
	 *
	 * draft     -> generated by Claude, awaiting human review. NOT sendable yet.
	 * approved  -> a human clicked "Approve & Send"; queued.
	 * sending   -> cron is draining the recipient list in batches.
	 * sent      -> finished.
	 * failed    -> aborted (e.g. no recipients, or a fatal send error).
	 */
	public static function campaigns_table() {
		global $wpdb;
		return $wpdb->prefix . 'brm_campaigns';
	}

	/**
	 * Recipients table name.
	 */
	public static function recipients_table() {
		global $wpdb;
		return $wpdb->prefix . 'brm_recipients';
	}

	/**
	 * Create/upgrade tables on activation.
	 */
	public static function install() {
		global $wpdb;

		require_once ABSPATH . 'wp-admin/includes/upgrade.php';

		$charset_collate = $wpdb->get_charset_collate();
		$campaigns       = self::campaigns_table();
		$recipients      = self::recipients_table();

		$sql_campaigns = "CREATE TABLE {$campaigns} (
			id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
			subject TEXT NOT NULL,
			body LONGTEXT NOT NULL,
			prompt TEXT NULL,
			model VARCHAR(64) NOT NULL DEFAULT '',
			status VARCHAR(20) NOT NULL DEFAULT 'draft',
			send_offset BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
			recipient_count BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
			sent_count BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
			fail_count BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
			created_by BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
			approved_by BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
			updated_at DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
			approved_at DATETIME NULL,
			sent_at DATETIME NULL,
			PRIMARY KEY  (id),
			KEY status (status)
		) {$charset_collate};";

		$sql_recipients = "CREATE TABLE {$recipients} (
			id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
			email VARCHAR(190) NOT NULL,
			name VARCHAR(190) NOT NULL DEFAULT '',
			status VARCHAR(20) NOT NULL DEFAULT 'subscribed',
			unsubscribe_token VARCHAR(64) NOT NULL DEFAULT '',
			created_at DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
			unsubscribed_at DATETIME NULL,
			PRIMARY KEY  (id),
			UNIQUE KEY email (email),
			KEY status (status)
		) {$charset_collate};";

		dbDelta( $sql_campaigns );
		dbDelta( $sql_recipients );

		update_option( 'brm_db_version', self::DB_VERSION );
	}

	/**
	 * Insert a generated draft. Always lands as 'draft' — never sendable on creation.
	 *
	 * @param array $data subject, body, prompt, model.
	 * @return int|false Inserted campaign ID or false.
	 */
	public static function insert_draft( $data ) {
		global $wpdb;

		$now = current_time( 'mysql' );

		$ok = $wpdb->insert(
			self::campaigns_table(),
			array(
				'subject'    => (string) $data['subject'],
				'body'       => (string) $data['body'],
				'prompt'     => isset( $data['prompt'] ) ? (string) $data['prompt'] : '',
				'model'      => isset( $data['model'] ) ? (string) $data['model'] : '',
				'status'     => 'draft',
				'created_by' => get_current_user_id(),
				'created_at' => $now,
				'updated_at' => $now,
			),
			array( '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%s' )
		);

		return $ok ? (int) $wpdb->insert_id : false;
	}

	/**
	 * Fetch one campaign row.
	 *
	 * @param int $id Campaign ID.
	 * @return object|null
	 */
	public static function get_campaign( $id ) {
		global $wpdb;
		$table = self::campaigns_table();
		return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE id = %d", $id ) );
	}

	/**
	 * List campaigns, newest first.
	 *
	 * @param int $limit Max rows.
	 * @return array
	 */
	public static function list_campaigns( $limit = 50 ) {
		global $wpdb;
		$table = self::campaigns_table();
		return $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$table} ORDER BY id DESC LIMIT %d", $limit ) );
	}

	/**
	 * Update a campaign row.
	 *
	 * @param int   $id     Campaign ID.
	 * @param array $fields Column => value.
	 * @return bool
	 */
	public static function update_campaign( $id, $fields ) {
		global $wpdb;
		$fields['updated_at'] = current_time( 'mysql' );
		return false !== $wpdb->update( self::campaigns_table(), $fields, array( 'id' => (int) $id ) );
	}

	/**
	 * Count subscribed recipients.
	 *
	 * @return int
	 */
	public static function count_subscribed() {
		global $wpdb;
		$table = self::recipients_table();
		return (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table} WHERE status = 'subscribed'" );
	}

	/**
	 * Fetch a batch of subscribed recipients, ordered by id, for drip sending.
	 *
	 * Ordering by id plus a strictly-increasing offset guarantees each recipient
	 * is visited at most once across batches, so no duplicate sends.
	 *
	 * @param int $after_id Return rows with id greater than this.
	 * @param int $limit    Batch size.
	 * @return array
	 */
	public static function get_subscribed_batch( $after_id, $limit ) {
		global $wpdb;
		$table = self::recipients_table();
		return $wpdb->get_results(
			$wpdb->prepare(
				"SELECT id, email, name, unsubscribe_token FROM {$table}
				 WHERE status = 'subscribed' AND id > %d
				 ORDER BY id ASC LIMIT %d",
				$after_id,
				$limit
			)
		);
	}

	/**
	 * Add or update a recipient. Emails are normalised to lowercase so the
	 * UNIQUE index dedupes the list at the source.
	 *
	 * @param string $email Email.
	 * @param string $name  Display name.
	 * @return bool True if a new row was inserted.
	 */
	public static function upsert_recipient( $email, $name = '' ) {
		global $wpdb;

		$email = strtolower( sanitize_email( $email ) );
		if ( ! is_email( $email ) ) {
			return false;
		}

		$table    = self::recipients_table();
		$existing = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE email = %s", $email ) );

		if ( $existing ) {
			// Don't silently resurrect someone who opted out: leave status alone.
			if ( $name ) {
				$wpdb->update( $table, array( 'name' => $name ), array( 'id' => (int) $existing ) );
			}
			return false;
		}

		$wpdb->insert(
			$table,
			array(
				'email'             => $email,
				'name'              => sanitize_text_field( $name ),
				'status'            => 'subscribed',
				'unsubscribe_token' => self::generate_token(),
				'created_at'        => current_time( 'mysql' ),
			),
			array( '%s', '%s', '%s', '%s', '%s' )
		);

		return (bool) $wpdb->insert_id;
	}

	/**
	 * Mark a recipient unsubscribed by token. Returns the recipient row or null.
	 *
	 * @param string $token Unsubscribe token.
	 * @return object|null
	 */
	public static function unsubscribe_by_token( $token ) {
		global $wpdb;

		$token = preg_replace( '/[^a-f0-9]/', '', (string) $token );
		if ( strlen( $token ) < 32 ) {
			return null;
		}

		$table     = self::recipients_table();
		$recipient = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE unsubscribe_token = %s", $token ) );
		if ( ! $recipient ) {
			return null;
		}

		if ( 'unsubscribed' !== $recipient->status ) {
			$wpdb->update(
				$table,
				array(
					'status'          => 'unsubscribed',
					'unsubscribed_at' => current_time( 'mysql' ),
				),
				array( 'id' => (int) $recipient->id )
			);
		}

		return $recipient;
	}

	/**
	 * A random, URL-safe token for unsubscribe links.
	 *
	 * @return string
	 */
	public static function generate_token() {
		return bin2hex( random_bytes( 16 ) );
	}
}
