#!/usr/bin/env python3
"""
Inject SEO + social-share (Open Graph / Twitter) meta into every site page,
and (re)generate sitemap.xml and robots.txt. Idempotent — safe to re-run.

    python3 tools/inject_seo.py

The block for each page is written between HTML markers, so re-running replaces
it in place rather than duplicating. Derives og:title / description from each
page's existing <title> and <meta name="description">.

IMPORTANT: set BASE to the real production domain before deploying — Open Graph
image URLs must be absolute, so social scrapers need the true host.
"""
import os
import re
import datetime

BASE = "https://cp17.org"   # production domain
SITE_NAME = "The Cardinal Companion"

MARK_START = "<!-- seo:meta (generated by tools/inject_seo.py — do not edit by hand) -->"
MARK_END = "<!-- /seo:meta -->"

# page path (repo-relative) -> og card basename in assets/og/
PAGE_OG = {
    "index.html": "home",
    "books/promise.html": "promise",
    "books/toolkit.html": "toolkit",
    "free-guide/index.html": "checklist",
    "free-guide/caregivers-first-week-checklist.html": "checklist",
    "free-guide/grief.html": "grief",
    "free-guide/first-30-days-of-grief.html": "grief",
    "free-guide/children.html": "children",
    "free-guide/helping-children-grieve.html": "children",
    "free-guide/library.html": "library",
    "free-guide/thank-you.html": "library",
    "newsletter/index.html": "newsletter",
    "resources/index.html": "library",
}
DEFAULT_OG = "default"

# og:type article for the readable guides
ARTICLE_PAGES = {
    "free-guide/caregivers-first-week-checklist.html",
    "free-guide/first-30-days-of-grief.html",
    "free-guide/helping-children-grieve.html",
}
# keep out of the index (still followed)
NOINDEX = {"404.html", "free-guide/thank-you.html"}


def canonical(rel):
    if rel == "index.html":
        return BASE + "/"
    if rel.endswith("/index.html"):
        return BASE + "/" + rel[:-len("index.html")]
    return BASE + "/" + rel


def esc(s):
    return (s.replace("&", "&amp;").replace('"', "&quot;")
             .replace("<", "&lt;").replace(">", "&gt;"))


def find_pages(root):
    pages = []
    for dirpath, _dirs, files in os.walk(root):
        if "/.git" in dirpath or dirpath.endswith("/tools"):
            continue
        for f in files:
            if f.endswith(".html"):
                rel = os.path.relpath(os.path.join(dirpath, f), root)
                pages.append(rel.replace(os.sep, "/"))
    return sorted(pages)


def jsonld(rel, url, title, desc, og_url):
    if rel == "index.html":
        data = ('{"@context":"https://schema.org","@type":"WebSite",'
                '"name":"%s","url":"%s","description":"%s",'
                '"publisher":{"@type":"Organization","name":"%s","url":"%s","logo":"%s/assets/og/default.png"}}'
                % (SITE_NAME, BASE + "/", esc(desc), SITE_NAME, BASE + "/", BASE))
        return data
    if rel in ("books/promise.html", "books/toolkit.html"):
        name = title.split(" — ")[0]
        data = ('{"@context":"https://schema.org","@type":"Book",'
                '"name":"%s","url":"%s","image":"%s","description":"%s",'
                '"publisher":{"@type":"Organization","name":"%s","url":"%s"}}'
                % (esc(name), url, og_url, esc(desc), SITE_NAME, BASE + "/"))
        return data
    return None


def build_block(rel):
    og = PAGE_OG.get(rel, DEFAULT_OG)
    og_url = "%s/assets/og/%s.png" % (BASE, og)
    url = canonical(rel)
    otype = "article" if rel in ARTICLE_PAGES else "website"
    robots = "noindex,follow" if rel in NOINDEX else "index,follow"
    return og_url, url, otype, robots


def inject(path, rel):
    with open(path, encoding="utf-8") as f:
        html = f.read()

    tm = re.search(r"<title>(.*?)</title>", html, re.S)
    title = tm.group(1).strip() if tm else SITE_NAME
    dm = re.search(r'<meta\s+name="description"\s+content="(.*?)"\s*/?>', html, re.S)
    desc = dm.group(1).strip() if dm else ""

    og_url, url, otype, robots = build_block(rel)
    og_title = title
    lines = [
        MARK_START,
        '  <link rel="canonical" href="%s" />' % url,
        '  <meta name="robots" content="%s" />' % robots,
        '  <meta property="og:type" content="%s" />' % otype,
        '  <meta property="og:site_name" content="%s" />' % SITE_NAME,
        '  <meta property="og:title" content="%s" />' % esc(og_title),
        '  <meta property="og:description" content="%s" />' % esc(desc),
        '  <meta property="og:url" content="%s" />' % url,
        '  <meta property="og:image" content="%s" />' % og_url,
        '  <meta property="og:image:width" content="1200" />',
        '  <meta property="og:image:height" content="630" />',
        '  <meta property="og:image:alt" content="%s" />' % esc(og_title),
        '  <meta name="twitter:card" content="summary_large_image" />',
        '  <meta name="twitter:title" content="%s" />' % esc(og_title),
        '  <meta name="twitter:description" content="%s" />' % esc(desc),
        '  <meta name="twitter:image" content="%s" />' % og_url,
    ]
    ld = jsonld(rel, url, title, desc, og_url)
    if ld:
        lines.append('  <script type="application/ld+json">%s</script>' % ld)
    lines.append("  " + MARK_END)
    block = "\n".join(lines)

    # Remove any prior generated block (idempotent)
    html = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END),
                  "", html, flags=re.S).rstrip("\n")
    # normalize the blank line the removal may leave
    html = re.sub(r"\n[ \t]*\n(\s*</head>)", r"\n\1", html)

    # Insert after description meta, else after </title>, else after <head>
    if dm and dm.group(0) in html:
        anchor = dm.group(0)
    elif tm:
        anchor = "<title>%s</title>" % tm.group(1)
    else:
        anchor = "<head>"
    html = html.replace(anchor, anchor + "\n" + block, 1)
    html = re.sub(r"\n{3,}", "\n\n", html)  # keep re-runs from accreting blank lines

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return url, rel not in NOINDEX


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    pages = find_pages(root)
    today = datetime.date.today().isoformat()
    indexable = []
    for rel in pages:
        url, is_index = inject(os.path.join(root, rel), rel)
        if is_index:
            indexable.append(url)
        print("seo:", rel, "->", url, "" if is_index else "(noindex)")

    # sitemap.xml
    sm = ['<?xml version="1.0" encoding="UTF-8"?>',
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in indexable:
        prio = "1.0" if url == BASE + "/" else "0.7"
        sm += ["  <url>", "    <loc>%s</loc>" % url,
               "    <lastmod>%s</lastmod>" % today,
               "    <changefreq>monthly</changefreq>",
               "    <priority>%s</priority>" % prio, "  </url>"]
    sm.append("</urlset>")
    with open(os.path.join(root, "sitemap.xml"), "w") as f:
        f.write("\n".join(sm) + "\n")

    # robots.txt
    robots = ["User-agent: *", "Allow: /", "",
              "Sitemap: %s/sitemap.xml" % BASE, ""]
    with open(os.path.join(root, "robots.txt"), "w") as f:
        f.write("\n".join(robots))

    print("wrote sitemap.xml (%d urls) and robots.txt" % len(indexable))


if __name__ == "__main__":
    main()
