/**
 * Curated catalog of legitimate "free money for college" sources: federal and
 * state grants, large national scholarships, education tax credits, employer
 * tuition benefits, and military benefits.
 *
 * Amounts and deadlines are typical recent values and shift every award year —
 * each entry carries the official URL so the student verifies at the source.
 * None of these charge an application fee; anything that does is a scam.
 */

import type { Opportunity } from './types.ts';

export const CATALOG: Opportunity[] = [
  {
    id: 'pell-grant',
    name: 'Federal Pell Grant',
    sponsor: 'US Department of Education',
    kind: 'federal-grant',
    amountMin: 740,
    amountMax: 7395,
    renewable: true,
    deadline: { month: 6, day: 30 },
    url: 'https://studentaid.gov/understand-aid/types/grants/pell',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      maxHouseholdIncome: 100000,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      'The foundation of need-based aid — never repaid. One FAFSA form unlocks it (federal deadline June 30; file in the fall for the best state/school aid).',
  },
  {
    id: 'fseog',
    name: 'Federal Supplemental Educational Opportunity Grant (FSEOG)',
    sponsor: 'US Department of Education',
    kind: 'federal-grant',
    amountMin: 100,
    amountMax: 4000,
    renewable: true,
    deadline: { month: 6, day: 30 },
    url: 'https://studentaid.gov/understand-aid/types/grants/fseog',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      maxHouseholdIncome: 60000,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      'Extra grant for students with exceptional need, first-come first-served from each school’s pot — another reason to file the FAFSA early.',
  },
  {
    id: 'next-nc-scholarship',
    name: 'Next NC Scholarship',
    sponsor: 'State of North Carolina',
    kind: 'state-grant',
    amountMin: 3000,
    amountMax: 5000,
    renewable: true,
    deadline: { month: 6, day: 1 },
    url: 'https://www.cfnc.org/pay-for-college/next-nc-scholarship/',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      states: ['NC'],
      maxHouseholdIncome: 80000,
      requiresCitizenOrEligibleNoncitizen: true,
      requiresHalfTimePlus: true,
    },
    notes:
      'At least $3,000/yr at NC community colleges or $5,000/yr at UNC System schools for most households under ~$80k. Awarded automatically from the FAFSA.',
  },
  {
    id: 'coca-cola-scholars',
    name: 'Coca-Cola Scholars Program',
    sponsor: 'Coca-Cola Scholars Foundation',
    kind: 'scholarship',
    amountMin: 20000,
    amountMax: 20000,
    renewable: false,
    deadline: { month: 9, day: 30 },
    url: 'https://www.coca-colascholarsfoundation.org/apply/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 3.0,
      requiresCommunityService: true,
    },
    notes:
      '150 awards of $20,000 to high-school seniors with strong leadership and service. Application opens in August and closes early fall.',
  },
  {
    id: 'gates-scholarship',
    name: 'The Gates Scholarship',
    sponsor: 'Bill & Melinda Gates Foundation',
    kind: 'scholarship',
    amountMin: 20000,
    amountMax: 70000,
    renewable: true,
    deadline: { month: 9, day: 15 },
    url: 'https://www.thegatesscholarship.org/scholarship',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 3.3,
      maxHouseholdIncome: 60000,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      'Full cost of attendance not covered by other aid, for Pell-eligible minority high-school seniors. Highly competitive; the essay matters.',
  },
  {
    id: 'jack-kent-cooke',
    name: 'Jack Kent Cooke College Scholarship',
    sponsor: 'Jack Kent Cooke Foundation',
    kind: 'scholarship',
    amountMin: 40000,
    amountMax: 55000,
    renewable: true,
    deadline: { month: 11, day: 14 },
    url: 'https://www.jkcf.org/our-scholarships/college-scholarship-program/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 3.5,
      maxHouseholdIncome: 95000,
    },
    notes:
      'Up to $55,000/yr for high-achieving students with financial need — one of the largest private undergraduate scholarships.',
  },
  {
    id: 'dell-scholars',
    name: 'Dell Scholars Program',
    sponsor: 'Michael & Susan Dell Foundation',
    kind: 'scholarship',
    amountMin: 20000,
    amountMax: 20000,
    renewable: false,
    deadline: { month: 12, day: 1 },
    url: 'https://www.dellscholars.org/scholarship/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 2.4,
      maxHouseholdIncome: 60000,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      '$20,000 plus a laptop and ongoing support, aimed at gritty students who’ve overcome obstacles — GPA bar is intentionally low.',
  },
  {
    id: 'horatio-alger',
    name: 'Horatio Alger National Scholarship',
    sponsor: 'Horatio Alger Association',
    kind: 'scholarship',
    amountMin: 10000,
    amountMax: 25000,
    renewable: false,
    deadline: { month: 10, day: 25 },
    url: 'https://scholars.horatioalger.org/apply/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 2.0,
      maxHouseholdIncome: 65000,
      requiresCommunityService: true,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      'For students who have faced and overcome great adversity; household income under ~$65k. State and national award tiers.',
  },
  {
    id: 'elks-mvs',
    name: 'Elks Most Valuable Student Scholarship',
    sponsor: 'Elks National Foundation',
    kind: 'scholarship',
    amountMin: 4000,
    amountMax: 50000,
    renewable: true,
    deadline: { month: 11, day: 12 },
    url: 'https://www.elks.org/scholars/scholarships/mvs.cfm',
    criteria: {
      degreeLevels: ['high-school-senior'],
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      '500 four-year awards ($1,000–$12,500/yr) judged on scholarship, leadership, and need. No GPA cutoff — anyone can enter.',
  },
  {
    id: 'burger-king-scholars',
    name: 'Burger King Scholars Program',
    sponsor: 'Burger King Foundation',
    kind: 'scholarship',
    amountMin: 1000,
    amountMax: 50000,
    renewable: false,
    deadline: { month: 12, day: 15 },
    url: 'https://burgerkingfoundation.org/programs/burger-king-scholars/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 2.5,
    },
    notes:
      'Thousands of $1,000 awards plus larger tiers; open to US and Canadian seniors. A quick application with good odds.',
  },
  {
    id: 'amazon-future-engineer',
    name: 'Amazon Future Engineer Scholarship',
    sponsor: 'Amazon',
    kind: 'scholarship',
    amountMin: 40000,
    amountMax: 40000,
    renewable: true,
    deadline: { month: 1, day: 31 },
    url: 'https://www.amazonfutureengineer.com/scholarships',
    criteria: {
      degreeLevels: ['high-school-senior'],
      fields: ['stem'],
      maxHouseholdIncome: 90000,
    },
    notes:
      '$10,000/yr for four years plus a guaranteed paid Amazon internship offer, for students planning to study computer science.',
  },
  {
    id: 'equitable-excellence',
    name: 'Equitable Excellence Scholarship',
    sponsor: 'Equitable Foundation',
    kind: 'scholarship',
    amountMin: 2500,
    amountMax: 20000,
    renewable: true,
    deadline: { month: 12, day: 18 },
    url: 'https://equitable.com/foundation/equitable-excellence-scholarship',
    criteria: {
      degreeLevels: ['high-school-senior'],
      requiresCommunityService: true,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes: 'Rewards students who’ve led positive change through community service; hundreds of awards.',
  },
  {
    id: 'aotc',
    name: 'American Opportunity Tax Credit (AOTC)',
    sponsor: 'IRS',
    kind: 'tax-credit',
    amountMin: 0,
    amountMax: 2500,
    renewable: true,
    deadline: 'rolling',
    url: 'https://www.irs.gov/credits-deductions/individuals/aotc',
    criteria: {
      degreeLevels: ['undergraduate', 'high-school-senior'],
      requiresHalfTimePlus: true,
      maxHouseholdIncome: 180000,
    },
    notes:
      'Up to $2,500/yr back at tax time for each of the first four years of college (40% refundable even with zero tax owed). Claimed on the family’s return.',
  },
  {
    id: 'lifetime-learning-credit',
    name: 'Lifetime Learning Credit',
    sponsor: 'IRS',
    kind: 'tax-credit',
    amountMin: 0,
    amountMax: 2000,
    renewable: true,
    deadline: 'rolling',
    url: 'https://www.irs.gov/credits-deductions/individuals/llc',
    criteria: {
      degreeLevels: ['graduate', 'undergraduate'],
      maxHouseholdIncome: 180000,
    },
    notes:
      'Up to $2,000/yr with no four-year or half-time limit — the grad-school and part-timer counterpart to the AOTC (you can’t claim both for the same student).',
  },
  {
    id: 'employer-tuition-127',
    name: 'Employer Tuition Assistance (IRC §127)',
    sponsor: 'Your employer',
    kind: 'employer-benefit',
    amountMin: 0,
    amountMax: 5250,
    renewable: true,
    deadline: 'rolling',
    url: 'https://www.irs.gov/publications/p970',
    criteria: {
      requiresEmployment: true,
    },
    notes:
      'Many employers reimburse up to $5,250/yr tax-free (some, like Amazon/Starbucks/Chipotle, pay full tuition). Ask HR — this one is pure found money.',
  },
  {
    id: 'gi-bill',
    name: 'Post-9/11 GI Bill & military tuition assistance',
    sponsor: 'US Department of Veterans Affairs / DoD',
    kind: 'military-benefit',
    amountMin: 0,
    amountMax: 29920,
    renewable: true,
    deadline: 'rolling',
    url: 'https://www.va.gov/education/about-gi-bill-benefits/',
    criteria: {
      requiresMilitaryAffiliation: true,
    },
    notes:
      'Covers up to full in-state public tuition plus a housing stipend for service members, veterans, and (via transfer) their dependents.',
  },
  {
    id: 'cal-grant',
    name: 'Cal Grant',
    sponsor: 'State of California',
    kind: 'state-grant',
    amountMin: 1648,
    amountMax: 14588,
    renewable: true,
    deadline: { month: 3, day: 2 },
    url: 'https://www.csac.ca.gov/cal-grants',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      states: ['CA'],
      maxHouseholdIncome: 120000,
      requiresHalfTimePlus: true,
    },
    notes:
      'California’s big one: full UC/CSU systemwide tuition for qualifying students. The March 2 FAFSA/CADAA deadline is famously hard — miss it, wait a year.',
  },
  {
    id: 'ny-tap',
    name: 'New York Tuition Assistance Program (TAP)',
    sponsor: 'State of New York',
    kind: 'state-grant',
    amountMin: 500,
    amountMax: 5665,
    renewable: true,
    deadline: { month: 6, day: 30 },
    url: 'https://www.hesc.ny.gov/pay-for-college/apply-for-financial-aid/nys-tap.html',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      states: ['NY'],
      maxHouseholdIncome: 80000,
      requiresCitizenOrEligibleNoncitizen: true,
      requiresHalfTimePlus: true,
    },
    notes:
      'Up to $5,665/yr toward tuition at New York schools; apply through the FAFSA plus the state TAP application.',
  },
  {
    id: 'texas-grant',
    name: 'TEXAS Grant',
    sponsor: 'State of Texas',
    kind: 'state-grant',
    amountMin: 2000,
    amountMax: 8700,
    renewable: true,
    deadline: { month: 1, day: 15 },
    url: 'https://comptroller.texas.gov/programs/education/msp/funding/aid/grants.php',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      states: ['TX'],
      maxHouseholdIncome: 70000,
      requiresHalfTimePlus: true,
    },
    notes:
      'Covers roughly average public-university tuition and fees for Texans with need; the January priority deadline matters — funds run out.',
  },
  {
    id: 'fl-bright-futures',
    name: 'Florida Bright Futures',
    sponsor: 'State of Florida',
    kind: 'state-grant',
    amountMin: 4000,
    amountMax: 7000,
    renewable: true,
    deadline: { month: 8, day: 31 },
    url: 'https://www.floridastudentfinancialaidsg.org/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      states: ['FL'],
      minGpa: 3.0,
      requiresCommunityService: true,
    },
    notes:
      'Merit-based, not need-based: 75–100% of tuition at Florida publics for good grades, test scores, and service hours. Apply your senior year.',
  },
  {
    id: 'ga-hope',
    name: 'Georgia HOPE Scholarship',
    sponsor: 'State of Georgia',
    kind: 'state-grant',
    amountMin: 4500,
    amountMax: 7700,
    renewable: true,
    deadline: 'rolling',
    url: 'https://www.gafutures.org/hope-state-aid-programs/',
    criteria: {
      degreeLevels: ['high-school-senior', 'undergraduate'],
      states: ['GA'],
      minGpa: 3.0,
    },
    notes:
      'Merit aid for Georgians with a 3.0+: most of tuition at state schools, and the Zell Miller tier (3.7+) covers it all. Keep the GPA up to keep it.',
  },
  {
    id: 'questbridge',
    name: 'QuestBridge National College Match',
    sponsor: 'QuestBridge',
    kind: 'scholarship',
    amountMin: 50000,
    amountMax: 80000,
    renewable: true,
    deadline: { month: 9, day: 26 },
    url: 'https://www.questbridge.org/high-school-students/national-college-match',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 3.5,
      maxHouseholdIncome: 65000,
    },
    notes:
      'A full four-year scholarship to a partner college (Stanford, MIT, Yale…) for high-achieving, low-income students — most are first-generation. Life-changing if it hits.',
  },
  {
    id: 'ge-reagan',
    name: 'GE-Reagan Foundation Scholarship',
    sponsor: 'Ronald Reagan Presidential Foundation',
    kind: 'scholarship',
    amountMin: 40000,
    amountMax: 40000,
    renewable: true,
    deadline: { month: 1, day: 4 },
    url: 'https://www.reaganfoundation.org/education/scholarship-programs/ge-reagan-foundation-scholarship-program/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 3.0,
      requiresCommunityService: true,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes: '$10,000/yr for four years, rewarding leadership, drive, integrity, and citizenship.',
  },
  {
    id: 'cameron-impact',
    name: 'Cameron Impact Scholarship',
    sponsor: 'Bryan Cameron Education Foundation',
    kind: 'scholarship',
    amountMin: 20000,
    amountMax: 50000,
    renewable: true,
    deadline: { month: 9, day: 6 },
    url: 'https://www.bryancameroneducationfoundation.org/',
    criteria: {
      degreeLevels: ['high-school-senior'],
      minGpa: 3.7,
      requiresCommunityService: true,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      'Full-tuition, merit-based, need-blind four-year scholarship for 10–15 exceptional student leaders each year.',
  },
  {
    id: 'americorps-segal',
    name: 'AmeriCorps Segal Education Award',
    sponsor: 'AmeriCorps',
    kind: 'federal-grant',
    amountMin: 1000,
    amountMax: 7395,
    renewable: false,
    deadline: 'rolling',
    url: 'https://americorps.gov/members-volunteers/segal-americorps-education-award',
    criteria: {
      requiresCommunityService: true,
      requiresCitizenOrEligibleNoncitizen: true,
    },
    notes:
      'Serve a full AmeriCorps term and earn an education award pegged to the max Pell — usable for tuition or to pay down federal loans. Service first, money after.',
  },
];

export function findOpportunity(id: string): Opportunity | undefined {
  return CATALOG.find((o) => o.id === id);
}
